import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import NavBar from '@/components/ui/NavBar';
import Footer from '@/components/ui/Footer';
import ChatWindow from '@/components/Chat/ChatWindow';

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-roboto',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{
          __html: `
            // anti FOUC
            (function () {
              try {
                const themeStr = localStorage.getItem('theme-store');
                const themeJson = themeStr ? JSON.parse(themeStr) : {};
                const theme = themeJson.state ? themeJson.state.theme : 'system';

                const darkMode = window.matchMedia('(prefers-color-scheme: dark)').matches;

                if (theme === 'dark' || (theme === 'system' && darkMode)) {
                  document.documentElement.classList.add('dark');
                } else {
                  document.documentElement.classList.remove('dark');
                }
              } catch (e) { console.error('theme script failed', e); }
            })()`,
        }} />
      </head>
      <body className={`${roboto.variable} antialiased`}>
        <div className="min-h-screen flex flex-col">
          <NavBar />
          <main className="flex-grow flex flex-col items-center justify-center">
            {children}
          </main>
          <Footer />
        </div>
        <ChatWindow />
      </body>
    </html>
  );
}
